// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.DataAccess.Data;

#nullable disable

namespace WebStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231013111633_AddProductTableToDb")]
    partial class AddProductTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("WebStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Frank Herbert",
                            Description = "Before Matrix, before Star Wars, before Ender's Game and Neuromancer, there was Dune, one of the greatest science fiction novels ever written.",
                            ISBN = "978-0-340-96019-6",
                            Price = 169.0,
                            Price100 = 99.0,
                            Price50 = 129.0,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Fyodor Dostoevsky",
                            Description = "Rodion Raskolnikov is a handsome, yet impoverished student. Morally conflicted, he believes that extraordinary men who contribute much to society by their thinking are above the law, and in order to prove his theory, he decides to murder a grasping old money lender and, through unforeseen circumstances, her sister.  ",
                            ISBN = "978-1-78599-644-3",
                            Price = 89.0,
                            Price100 = 55.0,
                            Price50 = 69.0,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Scott Jurek",
                            Description = "Scott Jurek is a world-renowned ultramarathon champion who trains and races on a plant-based diet. He has appeared in two New York Times bestsellers, Born to Run and The 4-Hour Body.",
                            ISBN = "978-0-544-00231-9",
                            Price = 216.0,
                            Price100 = 128.0,
                            Price50 = 168.0,
                            Title = "Eat & Run"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
